'use strict';

const fs = require('fs');
const path = require('path');

// Maps bank ID → SVG filename in public/logos/
const ID_TO_FILE = {
  'markazi':      'centeral.svg',
  'sanat-madan':  'sanatmadan.svg',
  'mellat':       'mellat.svg',
  'refah':        'refahkargaran.svg',
  'maskan':       'maskan.svg',
  'sepah':        'sepah.svg',
  'keshavarzi':   'keshavarzi.svg',
  'meli':         'melli.svg',
  'tejarat':      'tejarat.svg',
  'saderat':      'saderat.svg',
  'tosee-saderat':'tosesaderat.svg',
  'post':         'post.svg',
  'tosee-taavon': 'tosetaavon.svg',
  'karafarin':    'karafarin.svg',
  'parsian':      'parsian.svg',
  'eghtesad':     'eghtesad.svg',
  'saman':        'saman.svg',
  'blu':          'blu.svg',
  'pasargad':     'pasargad.svg',
  'sarmaye':      'sarmaye.svg',
  'sina':         'sina.svg',
  'mehr-iran':    'mehriran.svg',
  'shahr':        'shahr.svg',
  'ayandeh':      'ayande.svg',
  'ansar':        'ansar.svg',
  'gardeshgari':  'gardeshgari.svg',
  'hekmat':       'hekmat.svg',
  'dey':          'day.svg',
  'iran-zamin':   'iranzamin.svg',
  'resalat':      'resalat.svg',
  'ghavamin':     'ghavvamin.svg',
};

const logosDir = path.join(__dirname, '..', 'public', 'logos');

const entries = Object.entries(ID_TO_FILE).map(([id, file]) => {
  const svg = fs.readFileSync(path.join(logosDir, file), 'utf8').trim();
  return `  ${JSON.stringify(id)}: ${JSON.stringify(svg)}`;
}).join(',\n');

const output = [
  "'use strict';",
  '',
  '// Auto-generated by scripts/build-logos.js — do not edit manually.',
  'const logos = {',
  entries,
  '};',
  '',
  'module.exports = { logos };',
  '',
].join('\n');

fs.writeFileSync(path.join(__dirname, '..', 'src', 'logos.js'), output);
console.log(`Generated src/logos.js (${Object.keys(ID_TO_FILE).length} logos)`);
